services:
  - type: web
    name: hcenzo-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URI
        sync: false # This will be set manually in Render dashboard
